apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
- addresses:
  - ip: 192.168.2.177
  ports:
  - port: 1990
    protocol: TCP
- addresses:
  - ip: 192.168.2.46
  ports:
  - port: 1990
    protocol: TCP
