apiVersion: v1
kind: PersistentVolume
metadata:
  name: gfs-datasets
spec:
  capacity:
    storage: 128Gi
  accessModes:
  - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: '/gv-test'
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
