apiVersion: v1
kind: PersistentVolume
metadata:
  name: gfs-models-node
spec:
  capacity:
    storage: 128Gi
  accessModes:
  - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: '/models'
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
