apiVersion: v1
kind: PersistentVolume
metadata:
  name: gfs-datasets-node
spec:
  capacity:
    storage: 256Gi
  accessModes:
  - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: '/datasets'
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
