apiVersion: v1
kind: PersistentVolume
metadata:
  name: gfs-postgres-node
spec:
  capacity:
    storage: 24Gi
  accessModes:
  - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: '/postgres'
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
