apiVersion: v1
kind: PersistentVolume
metadata:
  name: gfs-jobs-node
spec:
  capacity:
    storage: 48Gi
  accessModes:
  - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: '/jobs'
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
