apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
spec:
    capacity:
      storage: 100Gi
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Delete
    storageClassName: local-storage
    local:
      path: /mnt/disks/ssd1
